// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKiZ3ajecbuedwkjIPZPUGbp6JtC6l-qM',
    appId: '1:1073448126292:web:d44044a25fb6bd05736ac1',
    messagingSenderId: '1073448126292',
    projectId: 'nilego-mvp',
    authDomain: 'nilego-mvp.firebaseapp.com',
    storageBucket: 'nilego-mvp.firebasestorage.app',
    measurementId: 'G-69YZ8YNNDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ZHClEzxp4YJMstQ80dIFedGAXhGn4To',
    appId: '1:1073448126292:android:96dce2c10ddd757d736ac1',
    messagingSenderId: '1073448126292',
    projectId: 'nilego-mvp',
    storageBucket: 'nilego-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLEHsgS6yyaypCTOn7eu8qma6rjRhmZY',
    appId: '1:1073448126292:ios:a816a1ce5b4690cf736ac1',
    messagingSenderId: '1073448126292',
    projectId: 'nilego-mvp',
    storageBucket: 'nilego-mvp.firebasestorage.app',
    iosBundleId: 'com.example.nilegoMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyLEHsgS6yyaypCTOn7eu8qma6rjRhmZY',
    appId: '1:1073448126292:ios:a816a1ce5b4690cf736ac1',
    messagingSenderId: '1073448126292',
    projectId: 'nilego-mvp',
    storageBucket: 'nilego-mvp.firebasestorage.app',
    iosBundleId: 'com.example.nilegoMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKiZ3ajecbuedwkjIPZPUGbp6JtC6l-qM',
    appId: '1:1073448126292:web:202f831e7548061a736ac1',
    messagingSenderId: '1073448126292',
    projectId: 'nilego-mvp',
    authDomain: 'nilego-mvp.firebaseapp.com',
    storageBucket: 'nilego-mvp.firebasestorage.app',
    measurementId: 'G-JQVPD3JE3S',
  );

}